export const technicalSkilss = [
  { name: 'React', icon: '/icons/react.svg' },
  { name: 'JavaScript', icon: '/icons/javascript.svg' },
  { name: 'TypeScript', icon: '/icons/typescript.svg' },
  { name: 'Next.js', icon: '/icons/nextjs.svg' },
  { name: 'Redux', icon: '/icons/redux.svg' },
  { name: 'Redux Toolkit' },
  { name: 'Git', icon: '/icons/git.svg' },
  { name: 'Github', icon: '/icons/github.svg' },
  { name: 'OOP' },
  { name: 'React Native', icon: '/icons/react.svg' },
  { name: 'Tailwind', icon: '/icons/tailwind.svg' },
  { name: 'CSS', icon: '/icons/css.svg' },
  { name: 'Bootstrap', icon: '/icons/bootstrap.svg' },
  { name: 'Firebase', icon: '/icons/firebase.svg' },
  { name: 'HTML', icon: '/icons/html.svg' },
  { name: 'Microsoft Azure', icon: '/icons/azure.svg' },
  { name: 'SASS', icon: '/icons/sass.svg' },
  { name: 'Figma', icon: '/icons/figma.svg' },
];
